[phases.setup]
nixPkgs = ['php84', 'php84Extensions.pdo', 'php84Extensions.pdo_pgsql', 'php84Extensions.pgsql', 'php84Extensions.mbstring', 'php84Extensions.ctype']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'
